baseURL = "https://austindavidbrown.github.io"
languageCode = "en-us"
title = "Austin David Brown"
theme = "simple_modified"

# Pagination
paginate = 4
paginatePath = "page"

# Copyright
copyright = "© 2019 — Austin David Brown"

# Links format
[permalinks]
  post = "/post/:year/:month/:title/"
  
# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 1
  [[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 2
  [[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 3
  [[menu.main]]
    url = "/resume.html"
    name = "CV/Resume"
    weight = 4

# Footer
[[menu.footer]]
  url = "https://github.com/austindavidbrown"
  name = "GitHub"
  weight = 1
[[menu.footer]]
  url = "/post/index.xml"
  name = "RSS"
  weight = 2